package com.taskium.project.Domain.Enums;

public enum PermissionName {
    CREATE_TASK, VIEW_TASK, UPDATE_TASK, DELETE_TASK,
    CREATE_EVENT, VIEW_EVENT, UPDATE_EVENT, DELETE_EVENT, JOIN_EVENT, MANAGE_EVENT_USERS,
    VIEW_USER, UPDATE_USER, DELETE_USER, MANAGE_USERS,
    CREATE_NOTE, VIEW_NOTE, UPDATE_NOTE, DELETE_NOTE,
    CREATE_COMMENT, VIEW_COMMENT, DELETE_COMMENT,
    CREATE_REGULATION, VIEW_REGULATION, UPDATE_REGULATION, DELETE_REGULATION, ACCEPT_REGULATION,
    CREATE_TASK_CATEGORY, VIEW_TASK_CATEGORY, UPDATE_TASK_CATEGORY, DELETE_TASK_CATEGORY,
    CREATE_TASK_STATUS, VIEW_TASK_STATUS, UPDATE_TASK_STATUS, DELETE_TASK_STATUS,
    CREATE_EVENT_TYPE, VIEW_EVENT_TYPE, UPDATE_EVENT_TYPE, DELETE_EVENT_TYPE,
    CREATE_PARTICIPATION_STATUS, VIEW_PARTICIPATION_STATUS, UPDATE_PARTICIPATION_STATUS, DELETE_PARTICIPATION_STATUS,
    MANAGE_ROLES, MANAGE_PERMISSIONS
}

